name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Deploy to Hugging Face Spaces
        run: |
          if [ -z "${{ secrets.HF_SPACE_NAME }}" ]; then
            echo "Error: HF_SPACE_NAME is not set. Please add it as a repository secret."
            exit 1
          fi
          
          if [ -z "${{ secrets.HF_TOKEN }}" ]; then
            echo "Error: HF_TOKEN is not set. Please add it as a repository secret."
            exit 1
          fi
          
          echo "Deploying to Hugging Face Space: ${{ secrets.HF_SPACE_NAME }}"
          python -c "from huggingface_hub import HfApi; HfApi().upload_folder(folder_path='.', repo_id='${{ secrets.HF_SPACE_NAME }}', repo_type='space', token='${{ secrets.HF_TOKEN }}', ignore_patterns=['.*', 'venv/*', '__pycache__/*'])" 